version: '1'

services:
  pg_db:
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: "Agregactus"
      POSTGRES_USER: "agregactus_administrator"
      POSTGRES_PASSWORD: "xxxx"
    networks:
      - agregactus_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  agregactus:
    build: .
    environment:
      DB_HOST: "pg_db"
      DB_NAME: "Agregactus"
      DB_USER: "agregactus_administrator"
      DB_PASSWORD: "xxxx"
      DB_PORT: "5432"
      OPENAI_API_KEY: "sk-xxx"
      EMAIL_SENDER_ADDRESS: "xxx@gmail.com"
      EMAIL_SENDER_PASSWORD: "xxxx"
      EMAIL_RECEIVER_ADDRESS: "xxx@gmail.com"
    stdin_open: true
    tty: true
    depends_on:
      - pg_db
    networks:
      - agregactus_network
    restart: always

networks:
  agregactus_network:

volumes:
  pg_data: